### ISSUE TITLE
An issue with instructions for GPG4Win verification

### ISSUE THREAD

**Issue by Spurlos** [torproject/support#11]
After install Gpg4Win, gpg and gpgv commands are still not available using command line, so I can't execute this command:
`gpg --auto-key-locate nodefault,wkd --locate-keys torbrowser@torproject.org`

Have been able to find and add the Tor Developers key using Kleopatra:
![image](https://user-images.githubusercontent.com/667533/63642220-d622b800-c6c4-11e9-8cbd-ab50367050df.png)

But I can't verify the install with asc file provided (using Kleopatra):
![image](https://user-images.githubusercontent.com/667533/63642234-ff434880-c6c4-11e9-9b5a-4f8df92edebf.png)

Audit log:
```
gpg: Signature made 07/08/19 14:03:49 E. Europe Daylight Time
gpg:                using RSA key EB774491D9FF06E2
gpg: Can't check signature: No public key
```

But if I search for the RSA key mentioned in the log, i'll find the same exact key that was installed before:
![image](https://user-images.githubusercontent.com/667533/63642322-3e25ce00-c6c6-11e9-96d6-97add4bf96e8.png)

What I am doing wrong?

**Comment by aadibajpai** [comment]
I'm not sure why the gpg commands don't seem to work for you, are they accessible via your path?

For example, I checked where gpg was installed on my PC:
```
C:\Users\aadibajpai>where gpg
C:\Program Files (x86)\GnuPG\bin\gpg.exe
```

**Comment by Spurlos** [comment]
Well it works now.
```
C:\Users\Spurlos>where gpg
C:\Program Files (x86)\GnuPG\bin\gpg.exe

C:\Users\Spurlos>gpg --auto-key-locate nodefault,wkd --locate-keys torbrowser@torproject.org
gpg: key 4E2C6E8793298290: "Tor Browser Developers (signing key) <torbrowser@torproject.org>" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1
pub   rsa4096 2014-12-15 [C] [expires: 2020-08-24]
      EF6E286DDA85EA2A4BA7DE684E2C6E8793298290
uid           [  full  ] Tor Browser Developers (signing key) <torbrowser@torproject.org>
sub   rsa4096 2018-05-26 [S] [expires: 2020-09-12]
```

Guess a session restart is a must for gpg to be available in users command list. It wasn't available just after GPG4Win installation.

**Comment by aadibajpai** [comment]
> Well it works now.
> 
> ```
> C:\Users\Spurlos>where gpg
> C:\Program Files (x86)\GnuPG\bin\gpg.exe
> 
> C:\Users\Spurlos>gpg --auto-key-locate nodefault,wkd --locate-keys torbrowser@torproject.org
> gpg: key 4E2C6E8793298290: "Tor Browser Developers (signing key) <torbrowser@torproject.org>" not changed
> gpg: Total number processed: 1
> gpg:              unchanged: 1
> pub   rsa4096 2014-12-15 [C] [expires: 2020-08-24]
>       EF6E286DDA85EA2A4BA7DE684E2C6E8793298290
> uid           [  full  ] Tor Browser Developers (signing key) <torbrowser@torproject.org>
> sub   rsa4096 2018-05-26 [S] [expires: 2020-09-12]
> ```
> 
> Guess a session restart is a must for gpg to be available in users command list. It wasn't available just after GPG4Win installation.
> 
> Thanks for help!

Great!
