### ISSUE TITLE
"How to uninstall" is wrong on osx

### ISSUE THREAD

**Issue by armadev** [torproject/support#12]
https://support.torproject.org/tbb/tbb-28/ says that all you need to do is find the directory you installed tor browser to, and delete that.

But that isn't true on OSX: there, you need to not only delete the tor browser directory, but also find the profile data directory in /Library/ or something and delete that too.

(The profile data directory is separate because Apple's signing requirements mean that we're not allowed to modify the thing that got installed with a signature.)

GeKo is a good person for asking how exactly to describe this /Library/ thing.

**Comment by mpguerra** [comment]
This could be a good one for the Documentation Hackathon

**Comment by mpguerra** [comment]
@emmapeel2 would you say this can be closed now?

**Comment by emmapeel2** [comment]
> @emmapeel2 would you say this can be closed now?

I could not get reviews from the tbb team yet. I thought maybe to wait until releases is done to ping gk or boklm.

**Comment by emmapeel2** [comment]
also there is pending related changes at https://github.com/torproject/manual/pull/28

**Comment by mpguerra** [comment]
closed by 5da40e697bfc27f6e700c06eea571206d8c277dd and 56e150162de52c43f0cb77706aff3fc5af02ea58
