### ISSUE TITLE
update tor mobile section with new Tor Browser for Android

### ISSUE THREAD

**Issue by emmapeel2** [torproject/support#9]
Several files in the support portal need to be updated to reflect the new tba:

https://github.com/torproject/support/blob/master/content/tormobile/tormobile-5/contents.lr
https://github.com/torproject/support/blob/master/content/tormobile/tormobile-2/contents.lr
https://github.com/torproject/support/blob/master/content/tormobile/tormobile-1/contents.lr
https://github.com/torproject/support/blob/master/content/misc/glossary/contents.lr

probably more

**Comment by bitmold** [comment]
hi im happy to handle this and also while we are at it we prolly wanna nix everything related to Orfox

**Comment by emmapeel2** [comment]
great bitmold! we look forward to your PR!

**Comment by emmapeel2** [comment]
i think this ticket is also related to https://dip.torproject.org/web/support/issues/7
